name: 'NodeSecure Continuous Integration'
description: 'Pipeline of tools that identify dependencies vulnerabilities and track malicious code'
author: 'NodeSecure'

inputs:
  directory:
    description: 'Root directory from which the analyses will be run'
    required: false
  strategy:
    description: '@nodesecure/vuln vulnerability strategy'
    required: false
    default: 'npm'
  vulnerabilities:
    description: 'Vulnerability severity threshold'
    required: false
    default: 'all'
  warnings:
    description: 'Action when detecting warnings'
    required: false
    default: 'all'
  reporters:
    description: 'Pipeline reporters'
    required: false
    default: 'console'

runs:
  using: 'node16'
  main: 'index.js'

branding:
  icon: 'shield'
  color: purple